// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nintendo GameCube platform fighting game.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/7/75/Super_Smash_Bros_Melee_box_art.png",
                            Price = 9.99m,
                            Title = "Super Smash Brothers: Melee"
                        },
                        new
                        {
                            Id = 2,
                            Description = "First 3D open world RPG-style MegaMan Game on PS1 and N64",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/33/Rockman_DASH_re-release_cover_art.jpg",
                            Price = 8.99m,
                            Title = "MegaMan Legends"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Top-down JRPG where Solar Boy Django takes on Immortal Vampires",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/f/f0/Boktai_cover_art.jpg",
                            Price = 7.99m,
                            Title = "Boktai: The Sun Is in Your Hand!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
